env = HYPRCURSOR_THEME,blue-dot
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,blue-dot
env = XCURSOR_SIZE,24

source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/keybinds.conf

debug {
    disable_logs = true
}

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

general {
    gaps_in = 8
    gaps_out = 16
    border_size = 0
    col.active_border = rgba(7ec8d4cc)
    col.inactive_border = rgba(7ec8d466)
    layout = dwindle
}

decoration {
    rounding = 0
    blur {
        enabled = true
        size = 8
        passes = 3
        vibrancy = 0.2
    }
}

animations {
    enabled = true
    bezier = sharp, 0.25, 0.1, 0.25, 1.0
    animation = windows, 1, 2, sharp, popin 80%
    animation = fade, 1, 3, sharp
    animation = workspaces, 1, 3, sharp, slidevert
}

dwindle {
    preserve_split = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

$mainMod = SUPER
$terminal = kitty
$menu = rofi -show drun

# Window management
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive
bind = $mainMod, R, exec, $menu
bind = $mainMod, F, fullscreen
bind = $mainMod, T, togglefloating
bind = $mainMod, M, movetoworkspacesilent, 9
bind = $mainMod SHIFT, M, movetoworkspace, e+0

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod SHIFT, 1, movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, movetoworkspacesilent, 4

# Mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Screenshots
bind = , Print, exec, grim ~/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && grim - | wl-copy
bind = SHIFT, Print, exec, grim -g "$(slurp)" - | wl-copy

# Volume
binde = , XF86AudioRaiseVolume, exec, pamixer -i 5
binde = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMute, exec, pamixer -t

# Brightness
binde = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Media
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

# Autostart
exec-once = blueman-applet
source = ~/.config/hypr/monitors.conf



exec-once = python3 /home/drennant/navi-ui/launch.py



# Navi OS extras
exec-once = python3 /home/drennant/navi-ui/clock.py
exec-once = python3 /home/drennant/navi-ui/volumehud.py
exec-once = python3 /home/drennant/navi-ui/brightnesshud.py
exec-once = python3 /home/drennant/navi-ui/workspaceglitch.py
exec-once = bash -c "mkfifo /tmp/quickmenu_pipe 2>/dev/null; python3 /home/drennant/navi-ui/quickmenu/evdev_listener.py"
