bind = SUPER, grave, exec, python3 ~/.config/hypr/scripts/navi.py
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = , Shift_R, exec, python3 /home/drennant/navi-ui/quickmenu/quickmenu.py
bindr = , Shift_R, exec, echo go > /tmp/quickmenu_pipe
bind = SUPER SHIFT, R, exec, pkill -SIGINT wf-recorder || wf-recorder -f /home/drennant/Videos/$(date +%Y-%m-%d_%H-%M-%S).mp4 --audio
